// Full menu & cocktail-builder data for S'Historia
// Prawdziwe dane z restauracji i baru — DAL 1996

window.FULL_MENU = [
  {
    id: "antipasti", label: "Antipasti", icon: "✦",
    items: [
      { name: "Tagliere di salumi sardi", price: "15,00 €" },
      { name: "Tagliere di formaggi", price: "14,00 €", allergen: "7" },
      { name: "Insalata di polpo e patate", price: "16,00 €", allergen: "1·4·14" },
      { name: "Cozze alla marinara", price: "15,00 €", allergen: "14" },
      { name: "Misti mare cruditè", price: "30,00 €", allergen: "2·4·14" },
      { name: "Insalatona estiva", price: "18,00 €", desc: "Tonno / calamaro / salmone", allergen: "4·7·13" },
      { name: "Polpette di mare", price: "16,00 €", allergen: "1·2·3·4·6·11" },
      { name: "Antipasto del giorno", price: "18,00 €" },
      { name: "Degustazione 5 antipasti mare", price: "30,00 €", featured: true },
    ],
  },
  {
    id: "primi", label: "Primi", icon: "✦",
    items: [
      { name: "Risotto mare (min. 2)", price: "22,00 €", desc: "Cozze, vongole, crostacei", allergen: "2·4·7·14" },
      { name: "Tagliolini Rena", price: "20,00 €", desc: "Nero di seppia, calamari, gambero, basilico", allergen: "1·2·4·8", featured: true },
      { name: "Zuppa di pesce (prenotazione)", price: "32,00 €", desc: "Spada, cernia, gamberi, scampi", allergen: "2·4·14" },
      { name: "Gnocchetti alla sarda", price: "13,00 €", desc: "Salsiccia e pomodoro", allergen: "1·3·7" },
      { name: "Culurgiones", price: "18,00 €", desc: "Patate, formaggio, menta, pomodoro", allergen: "3·7·8", featured: true },
      { name: "Spaghetti alle vongole", price: "18,00 €", allergen: "12·13" },
      { name: "Spaghetti allo scoglio", price: "20,00 €", desc: "Cozze, vongole, crostacei", allergen: "2·4·12·13·14" },
    ],
  },
  {
    id: "secondi", label: "Secondi", icon: "✦",
    items: [
      { name: "Tonno alla griglia", price: "20,00 €", allergen: "4" },
      { name: "Calamari fritti", price: "20,00 €", allergen: "1·4·5" },
      { name: "Calamari arrosto", price: "20,00 €", allergen: "4" },
      { name: "Fritto misto di pesce", price: "25,00 €", desc: "Calamari, gamberi, filetto", allergen: "1·2·4·5·8" },
      { name: "Pesce pescato locale", price: "8,00 €", note: "all'etto" },
      { name: "Cotoletta", price: "14,00 €", allergen: "1·3·5·7·8" },
      { name: "Entrecôte", price: "20,00 €" },
      { name: "Filetto alla griglia", price: "26,00 €" },
      { name: "Costata di manzo", price: "6,50 €", note: "all'etto" },
      { name: "Costine di maiale", price: "18,00 €", allergen: "6·9" },
    ],
  },
  {
    id: "contorni", label: "Contorni", icon: "✦",
    items: [
      { name: "Verdure grigliate", price: "7,00 €" },
      { name: "Verdure saltate del giorno", price: "7,00 €" },
      { name: "Patate fritte", price: "6,00 €", allergen: "1" },
      { name: "Patate arrosto", price: "6,00 €" },
      { name: "Insalata mista", price: "5,00 €" },
    ],
  },
  {
    id: "pizze", label: "Pizze", icon: "✦",
    items: [
      { name: "Focaccia", price: "3,50 €", desc: "Olio, sale", allergen: "1" },
      { name: "Marinara", price: "5,00 €", desc: "Pomodoro, aglio", allergen: "1" },
      { name: "Margherita", price: "7,50 €", desc: "Pomodoro, mozzarella", allergen: "7" },
      { name: "Napoli", price: "8,50 €", desc: "Pomodoro, mozzarella, acciughe, capperi", allergen: "1·4·7" },
      { name: "Cardinale", price: "9,00 €", desc: "Pomodoro, mozzarella, prosciutto cotto", allergen: "1·7" },
      { name: "Boscaiola", price: "10,00 €", desc: "Pomodoro, mozzarella, prosciutto cotto, funghi freschi", allergen: "1·7" },
      { name: "Canadese", price: "10,00 €", desc: "Pomodoro, mozzarella, prosciutto cotto, wurstel", allergen: "1·7" },
      { name: "Paperino", price: "10,00 €", desc: "Pomodoro, mozzarella, patate fritte, wurstel", allergen: "1·5·7" },
      { name: "Calzone", price: "11,00 €", desc: "Pomodoro, mozzarella, prosciutto cotto, funghi freschi", allergen: "1·7" },
      { name: "Majore", price: "12,00 €", desc: "Pomodoro, mozzarella, salsiccia secca, peretta, pomodorini", allergen: "1·7" },
      { name: "Capitana", price: "12,00 €", desc: "Pomodoro, mozzarella, tonno, cipolla", allergen: "2·4·7" },
      { name: "Rena Matteu", price: "12,00 €", desc: "Pomodoro, mozzarella, mozzarella di bufala, pomodorini, basilico", allergen: "1·7" },
      { name: "Vegetariana", price: "12,00 €", desc: "Pomodoro, mozzarella, verdure miste", allergen: "7" },
      { name: "4 Formaggi", price: "12,00 €", desc: "Mozzarella, formaggi misti", allergen: "7" },
      { name: "Campagnola", price: "12,00 €", desc: "Mozzarella, pomodoro, salsiccia fresca, zucchine, pecorino", allergen: "1·7·8" },
      { name: "4 Mori", price: "14,00 €", desc: "Pomodoro, mozzarella, gamberi, rucola, peretta, pomodorini", allergen: "1·2·7" },
      { name: "Don Alessio", price: "14,00 €", desc: "Mozzarella, pomodoro, salsiccia fresca, melanzane, pecorino", allergen: "1·7·8" },
      { name: "Rustica", price: "15,00 €", desc: "Mozzarella, pancetta, burrata, olive taggiasche", allergen: "1·7·8" },
      { name: "Gallura", price: "15,00 €", desc: "Pomodoro, mozzarella, peretta, rucola, bottarga", allergen: "4·7" },
      { name: "S'Historia", price: "16,00 €", desc: "Pomodoro, mozzarella, gamberi, funghi freschi, bottarga", allergen: "1·2·4·7", featured: true },
      { name: "Don Giovanni", price: "16,00 €", desc: "Mozzarella, burrata, crudo, pomodorini, granella di mandorle", allergen: "5·7" },
      { name: "Frutti di mare", price: "18,00 €", desc: "Pomodoro, mozzarella, frutti di mare", allergen: "1·2·4·7" },
    ],
  },
];

window.DRINKS_MENU = {
  filters: [
    { id: "all", label: "Tutti" },
    { id: "cocktails", label: "Cocktails" },
    { id: "analcolici", label: "Analcolici" },
    { id: "smoothie", label: "Smoothie" },
    { id: "bibite", label: "Bibite" },
    { id: "birre-spina", label: "Birre spina" },
    { id: "birre-bottiglia", label: "Birre bottiglia" },
    { id: "birre-artigianali", label: "Artigianali" },
    { id: "gin", label: "Gin + Tonica" },
    { id: "vodka", label: "Vodka + Tonica" },
    { id: "tequila", label: "Tequila" },
    { id: "whisky", label: "Whisky" },
    { id: "rum", label: "Rum" },
    { id: "grappe", label: "Grappe" },
    { id: "amari", label: "Amari" },
    { id: "caffe", label: "Caffetteria" },
  ],
  items: [
    // ─── COCKTAILS ───────────────────────────────────────────────────────
    { cat: "cocktails", name: "Spritz", price: "6,00 €", desc: "Aperol, Prosecco, Soda", img: "https://www.thecocktaildb.com/images/media/drink/j9evx11504373665.jpg" },
    { cat: "cocktails", name: "Moscow Mule", price: "7,00 €", desc: "Vodka, Ginger Beer, Lime", img: "https://www.thecocktaildb.com/images/media/drink/3pylqc1504370988.jpg" },
    { cat: "cocktails", name: "Mojito", price: "7,00 €", desc: "Rum, Menta, Lime, Zucchero, Soda", img: "https://www.thecocktaildb.com/images/media/drink/metwgh1606770327.jpg" },
    { cat: "cocktails", name: "Americano", price: "7,00 €", desc: "Campari, Vermouth Rosso, Soda", img: "https://www.thecocktaildb.com/images/media/drink/709s6m1613655124.jpg" },
    { cat: "cocktails", name: "Dark N' Stormy", price: "8,00 €", desc: "Rum Scuro, Ginger Beer, Lime", img: "https://www.thecocktaildb.com/images/media/drink/t1tn0s1504374905.jpg" },
    { cat: "cocktails", name: "Margarita", price: "7,00 €", desc: "Tequila, Triple Sec, Lime", img: "https://www.thecocktaildb.com/images/media/drink/5noda61589575158.jpg" },
    { cat: "cocktails", name: "Daiquiri", price: "7,00 €", desc: "Rum, Lime, Zucchero", img: "https://www.thecocktaildb.com/images/media/drink/mrz9091589574515.jpg" },
    { cat: "cocktails", name: "Negroni", price: "7,00 €", desc: "Campari, Vermouth Rosso, Gin", img: "https://www.thecocktaildb.com/images/media/drink/qgdu971561574065.jpg" },
    { cat: "cocktails", name: "Caipiroska", price: "6,00 €", desc: "Vodka, Lime, Zucchero", img: "https://www.thecocktaildb.com/images/media/drink/jgvn7p1582484435.jpg" },
    { cat: "cocktails", name: "Caipirina", price: "6,00 €", desc: "Cachaca, Lime, Zucchero", img: "https://www.thecocktaildb.com/images/media/drink/jgvn7p1582484435.jpg" },
    { cat: "cocktails", name: "El Diablo", price: "8,00 €", desc: "Tequila, Crème de Cassis", img: "https://www.thecocktaildb.com/images/media/drink/quqyqp1480879103.jpg" },
    { cat: "cocktails", name: "Piña Colada", price: "9,00 €", desc: "Rum, Ananas, Cocco, Lime", img: "https://www.thecocktaildb.com/images/media/drink/upgsue1668419912.jpg" },

    // ─── ANALCOLICI ──────────────────────────────────────────────────────
    { cat: "analcolici", name: "Gin Fizz 00", price: "9,00 €", desc: "Gin 00, Lime, Zucchero, Soda", img: "https://www.thecocktaildb.com/images/media/drink/drtihp1606768397.jpg" },
    { cat: "analcolici", name: "Virgin Mojito", price: "8,00 €", desc: "Sprite, Menta, Lime, Zucchero", img: "https://www.thecocktaildb.com/images/media/drink/metwgh1606770327.jpg" },
    { cat: "analcolici", name: "Bellini 00", price: "8,00 €", desc: "Prosecco 00, Pesca", img: "https://www.thecocktaildb.com/images/media/drink/eaag491504367543.jpg" },
    { cat: "analcolici", name: "Virgin London Mule", price: "8,00 €", desc: "Gin 00, Gingerbeer, Lime", img: "https://www.thecocktaildb.com/images/media/drink/3pylqc1504370988.jpg" },
    { cat: "analcolici", name: "Virgin Colada", price: "9,00 €", desc: "Ananas, Cocco, Lime", img: "https://www.thecocktaildb.com/images/media/drink/upgsue1668419912.jpg" },
    { cat: "analcolici", name: "Spritz 00", price: "8,00 €", desc: "Bitter, Prosecco 00, Soda", img: "https://www.thecocktaildb.com/images/media/drink/j9evx11504373665.jpg" },

    // ─── SMOOTHIE ────────────────────────────────────────────────────────
    { cat: "smoothie", name: "Smoothie frutta fresca", price: "6,00 €", desc: "Con frutta fresca di stagione" },

    // ─── BIBITE ──────────────────────────────────────────────────────────
    { cat: "bibite", name: "Coca Cola", price: "4,00 €" },
    { cat: "bibite", name: "Coca Cola Zero", price: "4,00 €" },
    { cat: "bibite", name: "Fanta", price: "4,00 €" },
    { cat: "bibite", name: "Sprite", price: "4,00 €" },
    { cat: "bibite", name: "The Pesca", price: "4,00 €" },
    { cat: "bibite", name: "The Limone", price: "4,00 €" },
    { cat: "bibite", name: "Crodino", price: "4,00 €" },
    { cat: "bibite", name: "Aperol Soda", price: "4,00 €" },
    { cat: "bibite", name: "Bitter", price: "4,00 €" },
    { cat: "bibite", name: "Ginger Beer", price: "4,00 €" },
    { cat: "bibite", name: "Cocktail San Pellegrino", price: "4,00 €" },
    { cat: "bibite", name: "Red Bull", price: "4,00 €" },
    { cat: "bibite", name: "Succo", price: "4,00 €" },
    { cat: "bibite", name: "Acqua Tonica", price: "4,00 €" },
    { cat: "bibite", name: "Acqua Tonica Premium", price: "5,00 €" },
    { cat: "bibite", name: "Campari", price: "4,00 €" },
    { cat: "bibite", name: "Lemon Soda", price: "4,00 €" },
    { cat: "bibite", name: "Aranciata Amara", price: "4,00 €" },

    // ─── CAFFETTERIA ─────────────────────────────────────────────────────
    { cat: "caffe", name: "Caffè", price: "1,50 €" },
    { cat: "caffe", name: "Caffè Decaffeinato", price: "1,70 €" },
    { cat: "caffe", name: "Caffè Corretto", price: "2,50 €" },
    { cat: "caffe", name: "Caffè Macchiato Soia", price: "1,70 €" },
    { cat: "caffe", name: "Caffè Macchiato Ad", price: "1,70 €" },
    { cat: "caffe", name: "Cappuccino", price: "2,00 €" },
    { cat: "caffe", name: "Latte Macchiato", price: "2,50 €" },
    { cat: "caffe", name: "The Caldo", price: "2,50 €" },

    // ─── BIRRE SPINA ─────────────────────────────────────────────────────
    { cat: "birre-spina", name: "Heineken 0.20", price: "3,00 €" },
    { cat: "birre-spina", name: "Heineken 0.40", price: "5,00 €" },
    { cat: "birre-spina", name: "Ichnusa Non Filtrata 0.20", price: "3,50 €" },
    { cat: "birre-spina", name: "Ichnusa Non Filtrata 0.40", price: "6,00 €" },
    { cat: "birre-spina", name: "Messina 0.20", price: "3,50 €" },
    { cat: "birre-spina", name: "Messina 0.40", price: "6,00 €" },
    { cat: "birre-spina", name: "Moretti Rossa 0.20", price: "3,50 €" },
    { cat: "birre-spina", name: "Moretti Rossa 0.40", price: "6,00 €" },

    // ─── BIRRE BOTTIGLIA ─────────────────────────────────────────────────
    { cat: "birre-bottiglia", name: "Heineken", price: "3,50 €" },
    { cat: "birre-bottiglia", name: "Heineken 00", price: "3,50 €" },
    { cat: "birre-bottiglia", name: "Ichnusa", price: "3,00 €" },
    { cat: "birre-bottiglia", name: "Ichnusa Non Filtrata", price: "4,00 €" },
    { cat: "birre-bottiglia", name: "Ichnusa Al Limone", price: "3,00 €" },
    { cat: "birre-bottiglia", name: "Corona", price: "4,00 €" },
    { cat: "birre-bottiglia", name: "Peroni Senza Glutine", price: "3,50 €" },
    { cat: "birre-bottiglia", name: "Franziskaner", price: "5,00 €" },
    { cat: "birre-bottiglia", name: "Bulldog", price: "4,00 €" },
    { cat: "birre-bottiglia", name: "Warsteiner", price: "4,00 €" },

    // ─── BIRRE ARTIGIANALI 0.75 ──────────────────────────────────────────
    { cat: "birre-artigianali", name: "Sella Del Diavolo", price: "14,00 €", desc: "Bière De Garde, 0.75L" },
    { cat: "birre-artigianali", name: "Tuvi Tuvi", price: "14,00 €", desc: "Blond Ale, 0.75L" },
    { cat: "birre-artigianali", name: "Zagara", price: "14,00 €", desc: "Honey Amber Ale al miele d'arancio, 0.75L" },
    { cat: "birre-artigianali", name: "Friska", price: "14,00 €", desc: "Bière Blanche, 0.75L" },
    { cat: "birre-artigianali", name: "Macca Meda", price: "14,00 €", desc: "Strong American Amber Ale, 0.75L" },

    // ─── GIN + TONICA ────────────────────────────────────────────────────
    { cat: "gin", name: "Bombay + Tonica", price: "8,00 €" },
    { cat: "gin", name: "The Botanist + Tonica", price: "9,00 €" },
    { cat: "gin", name: "The Botanist Cask + Tonica", price: "10,00 €" },
    { cat: "gin", name: "Tanqueray + Tonica", price: "8,00 €" },
    { cat: "gin", name: "Tanqueray 00 + Tonica", price: "8,00 €" },
    { cat: "gin", name: "Pink Pepper + Tonica", price: "12,00 €" },
    { cat: "gin", name: "Gigi E Provence + Tonica", price: "10,00 €" },
    { cat: "gin", name: "Luz Limone + Tonica", price: "10,00 €" },
    { cat: "gin", name: "Sapling + Tonica", price: "10,00 €" },
    { cat: "gin", name: "Seri Pervas + Tonica", price: "10,00 €" },
    { cat: "gin", name: "Emporia + Tonica", price: "9,00 €" },
    { cat: "gin", name: "Genesi + Tonica", price: "10,00 €" },
    { cat: "gin", name: "Oyster Adriatic + Tonica", price: "9,00 €" },
    { cat: "gin", name: "Oyster Adriatico Citrus + Tonica", price: "10,00 €" },
    { cat: "gin", name: "L'Acrobatico + Tonica", price: "10,00 €" },
    { cat: "gin", name: "Palma Citrus + Tonica", price: "9,00 €" },
    { cat: "gin", name: "Palma Destilado + Tonica", price: "10,00 €" },
    { cat: "gin", name: "Tropical + Tonica", price: "9,00 €" },
    { cat: "gin", name: "Mediterraneo + Tonica", price: "10,00 €" },
    { cat: "gin", name: "Bus Spancer + Tonica", price: "9,00 €" },

    // ─── VODKA + TONICA ──────────────────────────────────────────────────
    { cat: "vodka", name: "Sapling + Tonica", price: "10,00 €" },
    { cat: "vodka", name: "Sapling Raspberry + Tonica", price: "10,00 €" },
    { cat: "vodka", name: "Paderewsky + Tonica", price: "9,00 €" },
    { cat: "vodka", name: "Eiko + Tonica", price: "10,00 €" },
    { cat: "vodka", name: "Beluga + Tonica", price: "10,00 €" },
    { cat: "vodka", name: "Beluga Rosa E Lime + Tonica", price: "10,00 €" },
    { cat: "vodka", name: "Beluga Allure Cl. 0.75", price: "300,00 €" },
    { cat: "vodka", name: "Beluga Gold Line Cl 0.75", price: "600,00 €" },

    // ─── TEQUILA ─────────────────────────────────────────────────────────
    { cat: "tequila", name: "Jose Cuervo", price: "4,00 €" },
    { cat: "tequila", name: "Jose Cuervo Reposada", price: "4,00 €" },
    { cat: "tequila", name: "Dobel", price: "12,00 €" },
    { cat: "tequila", name: "Espolon", price: "5,00 €" },
    { cat: "tequila", name: "1800", price: "8,00 €" },
    { cat: "tequila", name: "1800 Reposada", price: "10,00 €" },
    { cat: "tequila", name: "1800 Anejo", price: "10,00 €" },
    { cat: "tequila", name: "1800 Cristallino", price: "12,00 €" },
    { cat: "tequila", name: "Mezcal Marca Negra", price: "20,00 €" },

    // ─── WHISKY ──────────────────────────────────────────────────────────
    { cat: "whisky", name: "High Commissioner", price: "6,00 €" },
    { cat: "whisky", name: "Oro Pilla", price: "4,00 €" },
    { cat: "whisky", name: "Bushmills", price: "5,00 €" },
    { cat: "whisky", name: "Glen Grant", price: "5,00 €" },
    { cat: "whisky", name: "Teacher's", price: "5,00 €" },
    { cat: "whisky", name: "Jameson", price: "5,00 €" },
    { cat: "whisky", name: "Bankhall", price: "6,00 €" },
    { cat: "whisky", name: "John Crabbie", price: "5,00 €" },
    { cat: "whisky", name: "Bruichladdich", price: "9,00 €" },
    { cat: "whisky", name: "Bruichladdich 18 Anni", price: "24,00 €" },
    { cat: "whisky", name: "Bacche Gabrielsen", price: "9,00 €" },
    { cat: "whisky", name: "Port Charlotte", price: "6,00 €" },
    { cat: "whisky", name: "Woodford Reserve", price: "8,00 €" },
    { cat: "whisky", name: "Jack Daniel's", price: "5,00 €" },
    { cat: "whisky", name: "Jack Daniel's Fire", price: "7,00 €" },
    { cat: "whisky", name: "Jack Daniel's Apple", price: "7,00 €" },
    { cat: "whisky", name: "Jack Daniel's Honey", price: "7,00 €" },
    { cat: "whisky", name: "Gentleman Jack", price: "8,00 €" },
    { cat: "whisky", name: "Octomore 16.1", price: "24,00 €" },
    { cat: "whisky", name: "Octomore 16.2", price: "24,00 €" },
    { cat: "whisky", name: "Fujimi", price: "8,00 €" },
    { cat: "whisky", name: "Euyu", price: "8,00 €" },

    // ─── RUM ─────────────────────────────────────────────────────────────
    { cat: "rum", name: "Brugal", price: "6,00 €" },
    { cat: "rum", name: "Black Tears", price: "7,00 €" },
    { cat: "rum", name: "Pellerossa", price: "6,00 €" },
    { cat: "rum", name: "Don Papa Barocco", price: "9,00 €" },
    { cat: "rum", name: "Matusalem 23 Anni", price: "10,00 €" },
    { cat: "rum", name: "Santa Teresa", price: "10,00 €" },
    { cat: "rum", name: "Kraken", price: "6,00 €" },
    { cat: "rum", name: "Pampero Anniversario", price: "7,00 €" },
    { cat: "rum", name: "Arcane", price: "10,00 €" },
    { cat: "rum", name: "Torquoise Bay", price: "12,00 €" },
    { cat: "rum", name: "Anacaona", price: "12,00 €" },
    { cat: "rum", name: "Yellow Snake", price: "10,00 €" },
    { cat: "rum", name: "El Pasador De Oro Pasión", price: "15,00 €" },
    { cat: "rum", name: "El Pasador De Oro XO", price: "15,00 €" },
    { cat: "rum", name: "Bocathéva", price: "15,00 €" },

    // ─── GRAPPE ──────────────────────────────────────────────────────────
    // Bianca / Aromatica
    { cat: "grappe", name: "Nonino Fragolino", price: "6,00 €", desc: "Bianca/Aromatica" },
    { cat: "grappe", name: "Nonino Bianca", price: "4,00 €", desc: "Bianca/Aromatica" },
    { cat: "grappe", name: "Nonino Malvisano", price: "6,00 €", desc: "Bianca/Aromatica" },
    { cat: "grappe", name: "Nonino Gioiello", price: "8,00 €", desc: "Bianca/Aromatica" },
    { cat: "grappe", name: "Nonino Williams", price: "6,00 €", desc: "Bianca/Aromatica" },
    { cat: "grappe", name: "Nonino Vendemmia Riserva", price: "4,00 €", desc: "Bianca/Aromatica" },
    { cat: "grappe", name: "Nonino Prosecco Riserva", price: "4,50 €", desc: "Bianca/Aromatica" },
    { cat: "grappe", name: "Ginepro", price: "5,00 €", desc: "Bianca/Aromatica" },
    { cat: "grappe", name: "Anfora", price: "4,50 €", desc: "Bianca/Aromatica" },
    // Barricata
    { cat: "grappe", name: "Nonino Barricata", price: "4,00 €", desc: "Barricata" },
    { cat: "grappe", name: "Nonino Riserva 5 Anni", price: "11,00 €", desc: "Barricata" },
    { cat: "grappe", name: "Nonino Riserva 8 Anni", price: "16,00 €", desc: "Barricata" },
    { cat: "grappe", name: "Giare Gewürztraminer", price: "6,50 €", desc: "Barricata" },
    { cat: "grappe", name: "Giare Amarone", price: "10,00 €", desc: "Barricata" },
    { cat: "grappe", name: "Trentina", price: "4,00 €", desc: "Barricata" },
    { cat: "grappe", name: "Liberna", price: "4,00 €", desc: "Barricata" },
    { cat: "grappe", name: "18 Lune Whiskey", price: "6,00 €", desc: "Barricata" },
    { cat: "grappe", name: "18 Lune Rum", price: "6,50 €", desc: "Barricata" },

    // ─── AMARI ───────────────────────────────────────────────────────────
    { cat: "amari", name: "Amaro Del Capo", price: "4,00 €" },
    { cat: "amari", name: "Averna", price: "4,00 €" },
    { cat: "amari", name: "Baileys", price: "4,00 €" },
    { cat: "amari", name: "Branca Menta", price: "4,00 €" },
    { cat: "amari", name: "Cynar", price: "4,00 €" },
    { cat: "amari", name: "Fernet Branca", price: "4,00 €" },
    { cat: "amari", name: "Filuferru", price: "4,00 €" },
    { cat: "amari", name: "Ramazzotti", price: "4,00 €" },
    { cat: "amari", name: "Liquore Pistacchio", price: "4,00 €" },
    { cat: "amari", name: "Liquore Limone", price: "4,00 €" },
    { cat: "amari", name: "Jägermeister", price: "4,00 €" },
    { cat: "amari", name: "Limoncello", price: "4,00 €" },
    { cat: "amari", name: "Liquirizia", price: "4,00 €" },
    { cat: "amari", name: "Mirto", price: "4,00 €" },
    { cat: "amari", name: "Mirto Bianco", price: "4,00 €" },
    { cat: "amari", name: "Montenegro", price: "4,00 €" },
    { cat: "amari", name: "Sambuca", price: "4,00 €" },
    { cat: "amari", name: "Amaro Lucano", price: "4,00 €" },
    { cat: "amari", name: "Liquore Frutti Rossi", price: "4,00 €" },
    { cat: "amari", name: "Liquore Mango", price: "4,00 €" },
  ],
};


window.COCKTAIL_INGREDIENTS = [
  // RIGHT — DISTILLATI (alcohol)
  { id: "rum-bianco", label: "Rum bianco", group: "Distillati", side: "right", color: "#F2EAD8", volume: 25, isAlcohol: true },
  { id: "rum-coc", label: "Rum cocco", group: "Distillati", side: "right", color: "#E8DDC2", volume: 25, isAlcohol: true },
  { id: "vodka", label: "Vodka", group: "Distillati", side: "right", color: "#F8F4EC", volume: 25, isAlcohol: true },
  { id: "gin", label: "Gin", group: "Distillati", side: "right", color: "#E5EEEA", volume: 25, isAlcohol: true },
  { id: "tequila", label: "Tequila", group: "Distillati", side: "right", color: "#E8DDA0", volume: 25, isAlcohol: true },
  { id: "triple-sec", label: "Triple Sec", group: "Distillati", side: "right", color: "#F0E5C0", volume: 15, isAlcohol: true },
  { id: "whisky", label: "Whisky (Bourbon)", group: "Distillati", side: "right", color: "#C67123", volume: 25, isAlcohol: true },
  { id: "whisky-scotch", label: "Whisky (Scotch)", group: "Distillati", side: "right", color: "#B85D19", volume: 25, isAlcohol: true },
  { id: "caffe-liq", label: "Liquore caffè", group: "Distillati", side: "right", color: "#3A2418", volume: 20, isAlcohol: true },
  { id: "espresso", label: "Espresso", group: "Distillati", side: "right", color: "#2A1810", volume: 30, isAlcohol: false },
  // RIGHT — AMARI E LIQUORI
  { id: "aperol", label: "Aperol", group: "Amari e liquori", side: "right", color: "#F08540", volume: 30, isAlcohol: true },
  { id: "campari", label: "Campari", group: "Amari e liquori", side: "right", color: "#C84A2A", volume: 25, isAlcohol: true },
  { id: "mirto", label: "Mirto", group: "Amari e liquori", side: "right", color: "#5B2A4E", volume: 25, isAlcohol: true },
  { id: "blue-curacao", label: "Blue Curaçao", group: "Amari e liquori", side: "right", color: "#3DB6E0", volume: 20, isAlcohol: true },
  { id: "baileys", label: "Crema Whisky", group: "Amari e liquori", side: "right", color: "#E1D2B8", volume: 20, isAlcohol: true },
  // RIGHT — VINI
  { id: "prosecco", label: "Prosecco", group: "Vini", side: "right", color: "#F2EBC8", volume: 60, isAlcohol: true },
  { id: "vino-bianco", label: "Vino Bianco", group: "Vini", side: "right", color: "#EAE1B0", volume: 60, isAlcohol: true },
  { id: "vino-rosso", label: "Vino Rosso", group: "Vini", side: "right", color: "#4A0E1A", volume: 60, isAlcohol: true },

  // LEFT — BOLLICINE
  { id: "tonica", label: "Acqua tonica", group: "Bollicine", side: "left", color: "#E0EDF0", volume: 80, isAlcohol: false },
  { id: "soda", label: "Soda", group: "Bollicine", side: "left", color: "#E8F0F2", volume: 60, isAlcohol: false },
  { id: "cola", label: "Cola", group: "Bollicine", side: "left", color: "#1D0F08", volume: 80, isAlcohol: false },
  { id: "ginger", label: "Ginger beer", group: "Bollicine", side: "left", color: "#D8B860", volume: 80, isAlcohol: false },
  { id: "lemonsoda", label: "Lemonsoda", group: "Bollicine", side: "left", color: "#F2E060", volume: 60, isAlcohol: false },
  // LEFT — SUCCHI
  { id: "lime", label: "Lime", group: "Succhi", side: "left", color: "#9DC85A", volume: 20, isAlcohol: false },
  { id: "limone", label: "Limone", group: "Succhi", side: "left", color: "#F2DC4A", volume: 20, isAlcohol: false },
  { id: "arancia", label: "Arancia", group: "Succhi", side: "left", color: "#F0962D", volume: 30, isAlcohol: false },
  { id: "ananas", label: "Ananas", group: "Succhi", side: "left", color: "#F2D346", volume: 40, isAlcohol: false },
  { id: "pompelmo", label: "Pompelmo", group: "Succhi", side: "left", color: "#E8845A", volume: 30, isAlcohol: false },
  { id: "passion", label: "Passion fruit", group: "Succhi", side: "left", color: "#E8A030", volume: 20, isAlcohol: false },
  { id: "fragola", label: "Fragola", group: "Succhi", side: "left", color: "#D9405A", volume: 25, isAlcohol: false },
  // LEFT — DOLCE
  { id: "zucchero", label: "Zucchero di canna", group: "Dolce", side: "left", color: "#C9A87D", volume: 10, isAlcohol: false },
  { id: "sciroppo-cocco", label: "Sciroppo cocco", group: "Dolce", side: "left", color: "#F4ECDA", volume: 15, isAlcohol: false },
  { id: "granatina", label: "Granatina", group: "Dolce", side: "left", color: "#B81E3E", volume: 10, isAlcohol: false },
  { id: "miele", label: "Miele", group: "Dolce", side: "left", color: "#D9A030", volume: 10, isAlcohol: false },
  // LEFT — AROMI
  { id: "menta", label: "Menta", group: "Aromi", side: "left", color: "#5B9C68", volume: 5, isAlcohol: false },
  { id: "basilico", label: "Basilico", group: "Aromi", side: "left", color: "#4A7C53", volume: 5, isAlcohol: false },
  { id: "rosmarino", label: "Rosmarino", group: "Aromi", side: "left", color: "#3D6B4A", volume: 5, isAlcohol: false },
  { id: "sale", label: "Sale", group: "Aromi", side: "left", color: "#F0F0F0", volume: 2, isAlcohol: false },
];

// Pre-existing drinks (for "esiste già!" detection)
window.KNOWN_COCKTAILS = [
  { name: "Mojito", ingr: ["rum-bianco","lime","menta","zucchero","soda"], price: "7,00 €", origin: "Cuba" },
  { name: "Mojito Passion", ingr: ["rum-bianco","lime","menta","zucchero","passion"], price: "7,00 €", origin: "remix S'Historia" },
  { name: "Cuba Libre", ingr: ["rum-bianco","lime","cola"], price: "6,00 €", origin: "Cuba" },
  { name: "Piña Colada", ingr: ["rum-bianco","rum-coc","ananas","lime","sciroppo-cocco"], price: "9,00 €", origin: "Puerto Rico" },
  { name: "Gin Tonic", ingr: ["gin","tonica"], price: "8,00 €", origin: "classico" },
  { name: "Vodka Tonic", ingr: ["vodka","tonica"], price: "8,00 €", origin: "classico" },
  { name: "Moscow Mule", ingr: ["vodka","ginger","lime"], price: "7,00 €", origin: "USA" },
  { name: "Aperol Spritz", ingr: ["aperol","prosecco","soda","arancia"], price: "6,00 €", origin: "Veneto" },
  { name: "Margarita", ingr: ["tequila","triple-sec","lime","sale","zucchero"], price: "7,00 €", origin: "Messico" },
  { name: "Negroni", ingr: ["gin","campari","mirto"], price: "7,00 €", origin: "Firenze 1919" },
  { name: "4 Bianchi", ingr: ["tequila","vodka","rum-bianco","gin","lime","soda","zucchero"], price: "8,00 €", origin: "S'Historia" },
  { name: "Blue Long Island", ingr: ["rum-bianco","tequila","triple-sec","gin","limone","blue-curacao","soda","zucchero"], price: "9,00 €", origin: "USA" },
  { name: "Espresso Martini", ingr: ["vodka","caffe-liq","espresso","zucchero"], price: "7,00 €", origin: "London 1983" },
  { name: "Spritz", ingr: ["aperol","prosecco","soda"], price: "6,00 €", origin: "Veneto" },
  { name: "Americano", ingr: ["campari","vino-rosso","soda"], price: "7,00 €", origin: "Italia" },
  { name: "Dark N' Stormy", ingr: ["rum-bianco","ginger","lime"], price: "8,00 €", origin: "Bermuda" },
  { name: "Daiquiri", ingr: ["rum-bianco","lime","zucchero"], price: "7,00 €", origin: "Cuba" },
  { name: "Caipiroska", ingr: ["vodka","lime","zucchero"], price: "6,00 €", origin: "Brasile" },
  { name: "El Diablo", ingr: ["tequila","blue-curacao","lime"], price: "8,00 €", origin: "Messico" },
  { name: "Virgin Mojito", ingr: ["lime","menta","zucchero","soda"], price: "8,00 €", origin: "analcolico" },
  { name: "San Francisco", ingr: ["arancia","ananas","limone","pompelmo","granatina","soda"], price: "7,00 €", origin: "analcolico" },
  { name: "Tramonto Gallura", ingr: ["mirto","prosecco","arancia"], price: "9,00 €", origin: "firma S'Historia" },
  { name: "Cannonau Negroni", ingr: ["gin","campari","mirto"], price: "9,00 €", origin: "firma S'Historia" },
];

// Community cocktails (mock)
window.COMMUNITY_COCKTAILS = [
  { name: "Cuzzo Tropicale", by: "Marco", ingr: ["rum-bianco","ananas","passion","menta","lime"], likes: 24, comments: 8, comment: "Provato a luglio, da bere al tramonto. 10/10." },
  { name: "Nonna Drink", by: "Sara", ingr: ["mirto","limone","zucchero","menta"], likes: 18, comments: 5, comment: "Mia nonna avrebbe approvato. Mirto perfetto." },
  { name: "Sole di Rena", by: "Luca", ingr: ["gin","arancia","rosmarino","tonica"], likes: 31, comments: 12, comment: "Erbe di Gallura nel bicchiere." },
  { name: "Adriatico Blu", by: "Hannah", ingr: ["vodka","blue-curacao","limone","soda"], likes: 14, comments: 3, comment: "Sembra il mare in piscina." },
  { name: "Filu Verde", by: "Antonio", ingr: ["gin","menta","basilico","limone","zucchero"], likes: 27, comments: 9, comment: "Erbe + gin = magia." },
  { name: "Pompia Spritz", by: "Carlos", ingr: ["aperol","prosecco","pompelmo","soda"], likes: 9, comments: 2, comment: "Variante con pompelmo della casa." },
];
